// apps/sample-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'mylib-sample-web-components-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'sample-angular';
  items = JSON.stringify([
    {
      value: 'item-1',
      key: 'item-1',
      label: 'Item 1',
      disabled: false,
      dirty: false,
      checked: false,
    },
    {
      value: 'item-2',
      key: 'item-2',
      label: 'Item 2',
      disabled: false,
      dirty: false,
      checked: true,
    },
    {
      value: 'item-3',
      key: 'item-3',
      label: 'Item 3',
      disabled: false,
      dirty: false,
      checked: false,
    },
    {
      value: 'item-4',
      key: 'item-4',
      label: 'Item 4',
      disabled: false,
      dirty: false,
      checked: false,
    },
    {
      value: 'item-5',
      key: 'item-5',
      label: 'Item 5',
      disabled: false,
      dirty: false,
      checked: false,
    },
    {
      value: 'item-6',
      key: 'item-6',
      label: 'Item 6',
      disabled: false,
      dirty: false,
      checked: false,
    },
    {
      value: 'item-7',
      key: 'item-7',
      label: 'Item 7',
      disabled: false,
      dirty: false,
      checked: false,
    },
    {
      value: 'item-8',
      key: 'item-8',
      label: 'Item 8',
      disabled: false,
      dirty: false,
      checked: false,
    },
    {
      value: 'item-9',
      key: 'item-9',
      label: 'Item 9',
      disabled: false,
      dirty: false,
      checked: false,
    },
  ]);
  disabled = false;

  selectionChanged(e: any) {
    console.log(e, '----e');
  }

}

<mylib-button label="Angular button" icon="cmdEdit16"></mylib-button>

<mylib-checkbox-group
  [items]="items"
  label="Checkbox Group"
  [dirty]="false"
  [disabled]="disabled"
  (selectionChanged)="selectionChanged($event)"
>
</mylib-checkbox-group>

<mylib-command-bar [orientation]="'horizontal'" [shadowPosition]="'left'">
  <mylib-command-button
    [label]="'My Button'"
    icon="cmdAdd16"
    [orientation]="'horizontal'"
  ></mylib-command-button>

  <mylib-command-pipe></mylib-command-pipe>

  <mylib-command-button
    [label]="'My Button Label #2'"
    icon="cmdAlerts24"
    [orientation]="'horizontal'"
  ></mylib-command-button>

  <mylib-command-dropdown
    [label]="'My Button Dropdown Label'"
    icon="cmdAlerts24"
    [opened]="false"
    [orientation]="'horizontal'"
  >
    <mylib-command-dropdown-item [label]="'Dropdown item 1'" [disabled]="true">
    </mylib-command-dropdown-item>
    <mylib-command-dropdown-item
      [label]="'Dropdown item 2'"
      icon="cmdAdd16"
      icon-size="md"
    >
    </mylib-command-dropdown-item>
  </mylib-command-dropdown>

  <mylib-command-button
    [label]="'Command Group Label'"
    icon="cmdCancelCheckout24"
    [orientation]="'horizontal'"
    [disabled]="true"
  ></mylib-command-button>

  <mylib-command-pipe></mylib-command-pipe>

  <mylib-command-button
    [label]="'Command Group Label Command Group Label'"
    icon="cmdCancelCheckout24"
    [orientation]="'horizontal'"
  ></mylib-command-button>

  <mylib-command-dropdown
    [label]="'My Button Dropdown Label'"
    icon="cmdAlerts24"
    [opened]="false"
    [orientation]="'horizontal'"
  >
    <mylib-command-dropdown-item [label]="'Dropdown item 1'">
    </mylib-command-dropdown-item>
    <mylib-command-dropdown-item
      [label]="'Dropdown item 2'"
      icon="cmdAdd16"
      icon-size="md"
    >
    </mylib-command-dropdown-item>
  </mylib-command-dropdown>
</mylib-command-bar>

<br />
<h1>Splitter</h1>
<mylib-splitter>
  <mylib-splitter-item>
    <div>first item</div>
  </mylib-splitter-item>
  <mylib-splitter-item>
    <div>second item</div>
  </mylib-splitter-item>
  <mylib-splitter-item>
    <div>third item</div>
  </mylib-splitter-item>
  <mylib-splitter-item>
    <div>third item</div>
  </mylib-splitter-item>
</mylib-splitter>

<br />
<h1>Reactive Forms</h1>
<mylib-sample-web-form-components></mylib-sample-web-form-components>

<br />
<h1>Template Driven Forms</h1>
<mylib-sample-web-ng-model-components></mylib-sample-web-ng-model-components>

// apps/sample-vue/src/App.vue
<script setup lang="ts">
import HelloWorld from './components/HelloWorld.vue';
import TheWelcome from './components/TheWelcome.vue';

function handleClick(e: any) {
  console.log(e);
}

const items = JSON.stringify([
  {
    value: 'item-1',
    key: 'item-1',
    label: 'Item 1',
    disabled: false,
    dirty: false,
    checked: false,
  },
  {
    value: 'item-2',
    key: 'item-2',
    label: 'Item 2',
    disabled: false,
    dirty: false,
    checked: true,
  },
  {
    value: 'item-3',
    key: 'item-3',
    label: 'Item 3',
    disabled: false,
    dirty: false,
    checked: false,
  },
  {
    value: 'item-4',
    key: 'item-4',
    label: 'Item 4',
    disabled: false,
    dirty: false,
    checked: false,
  },
  {
    value: 'item-5',
    key: 'item-5',
    label: 'Item 5',
    disabled: false,
    dirty: false,
    checked: false,
  },
  {
    value: 'item-6',
    key: 'item-6',
    label: 'Item 6',
    disabled: false,
    dirty: false,
    checked: false,
  },
]);

function selectionChanged(e: any) {
  console.log('selection changed', e);
}
</script>

<template>
  <h1>Components</h1>
  <mylib-button label="mylib button" @click="handleClick"></mylib-button>

  <mylib-checkbox-group
    :items="items"
    label="Checkbox Group"
    dirty="false"
    @selectionChanged="selectionChanged($event)"
  >
  </mylib-checkbox-group>
  <mylib-icon name="cmdAbortTask24" size="md" type="font"></mylib-icon>
</template>

<style scoped>
#app {
  height: 100vh;
}

header {
  line-height: 1.5;
}

.logo {
  display: block;
  margin: 0 auto 2rem;
}

@media (min-width: 1024px) {
  header {
    display: flex;
    place-items: center;
    padding-right: calc(var(--section-gap) / 2);
  }

  .logo {
    margin: 0 2rem 0 0;
  }

  header .wrapper {
    display: flex;
    place-items: flex-start;
    flex-wrap: wrap;
  }
}
</style>
